/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.Abastecimento;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author marcos
 */
public class AbastecimentoConsultar extends javax.swing.JInternalFrame {

    /**
     * Creates new form AbastecimentoConsultar
     */
    public AbastecimentoConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTPlacaBusca = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAbastecimento = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jTTIPO = new javax.swing.JTextField();
        jLabelMarca = new javax.swing.JLabel();
        jLabelPLACA = new javax.swing.JLabel();
        jTPLACA = new javax.swing.JTextField();
        jLabelSeguro = new javax.swing.JLabel();
        jTValor = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTQuantidade = new javax.swing.JTextField();
        jTMotorista = new javax.swing.JTextField();
        jLabelDataIni = new javax.swing.JLabel();
        jTKM = new javax.swing.JTextField();
        jLabelDataIni1 = new javax.swing.JLabel();
        jLabelDataIni2 = new javax.swing.JLabel();
        jTDATA = new javax.swing.JTextField();
        jBAlterar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();

        jLabel1.setText("PLACA");

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTableAbastecimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TIPO", "PLACA", "QUANTIDADE", "VALOR", "MOTORISTA", "KM  VEICULO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAbastecimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAbastecimentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAbastecimento);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Abastecimento"));

        jLabel5.setText("ID");

        jTID.setEditable(false);
        jTID.setBackground(new java.awt.Color(255, 255, 204));

        jLabelMarca.setText("TIPO");

        jLabelPLACA.setText("PLACA");

        jLabelSeguro.setText("VALOR");

        jLabelCidade.setText("QUANTIDADE");

        jLabelDataIni.setText("MOTORISTA");

        jLabelDataIni1.setText("KM VEICULO");

        jLabelDataIni2.setText("DATA ABAST.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelPLACA)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTPLACA, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelMarca)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTTIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addComponent(jLabelSeguro)
                        .addGap(18, 18, 18)
                        .addComponent(jTValor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDataIni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDataIni1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDataIni2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTDATA, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMarca)
                    .addComponent(jTTIPO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPLACA)
                    .addComponent(jTPLACA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSeguro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataIni))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataIni1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTDATA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataIni2))
                .addGap(39, 39, 39))
        );

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTPlacaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBBuscar))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jBAlterar)
                .addGap(18, 18, 18)
                .addComponent(jBExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTPlacaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAlterar)
                    .addComponent(jBExcluir)
                    .addComponent(jBSair))
                .addGap(151, 151, 151))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        carregarTabela();
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTableAbastecimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAbastecimentoMouseClicked
        if (evt.getClickCount() == 1){

            jTID.setText((String)jTableAbastecimento.getValueAt(jTableAbastecimento.getSelectedRow(),0));
            jTTIPO.setText((String)jTableAbastecimento.getValueAt(jTableAbastecimento.getSelectedRow(),1));
            jTPLACA.setText((String)jTableAbastecimento.getValueAt(jTableAbastecimento.getSelectedRow(),2));
            jTQuantidade.setText((String)jTableAbastecimento.getValueAt(jTableAbastecimento.getSelectedRow(),3));
            jTValor.setText((String)jTableAbastecimento.getValueAt(jTableAbastecimento.getSelectedRow(),4));
            jTMotorista.setText((String)jTableAbastecimento.getValueAt(jTableAbastecimento.getSelectedRow(),5));
            jTKM.setText((String)jTableAbastecimento.getValueAt(jTableAbastecimento.getSelectedRow(),6));
            jTDATA.setText((String)jTableAbastecimento.getValueAt(jTableAbastecimento.getSelectedRow(),7));
            
            
        }
    }//GEN-LAST:event_jTableAbastecimentoMouseClicked

public void limpar(){
        
        //Limpa a tabela
        DefaultTableModel model = (DefaultTableModel)jTableAbastecimento.getModel(); 
        model.setNumRows(0);
        
        //Limpando os campos de texto
        jTID.setText("");
        jTTIPO.setText("");
        jTPLACA.setText("");
        jTQuantidade.setText("");
        jTValor.setText("");
        jTMotorista.setText("");
        jTKM.setText("");
        jTDATA.setText("");
        
       
        //Colocando o foco na text do nome artístico
        jTPlacaBusca.grabFocus();
      }
   
   public void carregarTabela(){
        Abastecimento abastecimento = new Abastecimento();
        ArrayList<Abastecimento> arrayDeAbastecimento = new ArrayList<Abastecimento>(); 
        
        //Chamando a busca no banco passando a data
        arrayDeAbastecimento = abastecimento.buscar(jTPlacaBusca.getText());
        
        //Apagando os dados da tabela para mostrar os novos
        limpar();
        
        DefaultTableModel model = (DefaultTableModel) jTableAbastecimento.getModel();
        
        //Andando na lista de tarefa e montando as linhas do TABLEMODEL
        for(int i=0; i<arrayDeAbastecimento.size(); i++){
            
            //Criando as colunas da linha i do TABLEMODEL
            String colunas[] = new String[8];
            colunas[0] = String.valueOf(arrayDeAbastecimento.get(i).getIdabastecimento());
            colunas[1] = String.valueOf(arrayDeAbastecimento.get(i).getTipo());
            colunas[2] = String.valueOf(arrayDeAbastecimento.get(i).getPlaca());
            colunas[3] = String.valueOf(arrayDeAbastecimento.get(i).getQuantidade());
            colunas[4] = String.valueOf(arrayDeAbastecimento.get(i).getValor());
            colunas[5] = String.valueOf(arrayDeAbastecimento.get(i).getMotorista());
            colunas[6] = String.valueOf(arrayDeAbastecimento.get(i).getKm());
            colunas[7] = String.valueOf(arrayDeAbastecimento.get(i).getData());
            
            //Adicionando uma linha no TABLEMODEL
            model.addRow(colunas);
        } 

        jTableAbastecimento.setModel(model);
    }      
    
    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
       Abastecimento objAbastecimento = new Abastecimento();

        objAbastecimento.setIdabastecimento(jTID.getText());
        objAbastecimento.setTipo(jTTIPO.getText());
        objAbastecimento.setPlaca(jTPLACA.getText());
        objAbastecimento.setQuantidade(jTQuantidade.getText());
        objAbastecimento.setValor(jTValor.getText());
        objAbastecimento.setMotorista(jTMotorista.getText());
        objAbastecimento.setKm(jTKM.getText());
        objAbastecimento.setData(jTDATA.getText());
        objAbastecimento.alterar();

        jTPlacaBusca.setText(objAbastecimento.getPlaca());
        carregarTabela();
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        Abastecimento objAbastecimento = new Abastecimento();
        objAbastecimento.setIdabastecimento(jTID.getText());
        objAbastecimento.setPlaca(jTPLACA.getText());
        objAbastecimento.setQuantidade(jTQuantidade.getText());
        objAbastecimento.setValor(jTValor.getText());
        objAbastecimento.setMotorista(jTMotorista.getText());
        objAbastecimento.setKm(jTKM.getText());
        objAbastecimento.setData(jTDATA.getText());
       

        objAbastecimento.excluir();

        jTPlacaBusca.setText(objAbastecimento.getPlaca());
        carregarTabela();
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        setVisible(isClosed);
    }//GEN-LAST:event_jBSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDataIni;
    private javax.swing.JLabel jLabelDataIni1;
    private javax.swing.JLabel jLabelDataIni2;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelPLACA;
    private javax.swing.JLabel jLabelSeguro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTDATA;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTKM;
    private javax.swing.JTextField jTMotorista;
    private javax.swing.JTextField jTPLACA;
    private javax.swing.JTextField jTPlacaBusca;
    private javax.swing.JTextField jTQuantidade;
    private javax.swing.JTextField jTTIPO;
    private javax.swing.JTextField jTValor;
    private javax.swing.JTable jTableAbastecimento;
    // End of variables declaration//GEN-END:variables
}
