/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.Multas;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marcos
 */
public class MultasConsultar extends javax.swing.JInternalFrame {

    /**
     * Creates new form MultasConsultar
     */
    public MultasConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTPlacaBusca = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMultas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTDESCRICAO = new javax.swing.JTextArea();
        jLabelPLACA = new javax.swing.JLabel();
        jTPLACA = new javax.swing.JTextField();
        jLabelSeguradora = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jTVALOR = new javax.swing.JTextField();
        jBAlterar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();

        jLabel1.setText("PLACA");

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTableMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "PLACA", "DESCRICAO", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMultas);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Multa"));

        jLabel5.setText("ID");

        jTID.setEditable(false);
        jTID.setBackground(new java.awt.Color(255, 255, 204));

        jTDESCRICAO.setColumns(20);
        jTDESCRICAO.setRows(5);
        jScrollPane2.setViewportView(jTDESCRICAO);

        jLabelPLACA.setText("PLACA");

        jLabelSeguradora.setText("DESCRIÇÃO");

        jLabelCidade.setText("VALOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelCidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTVALOR))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelPLACA)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTPLACA, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSeguradora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPLACA)
                    .addComponent(jTPLACA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTVALOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSeguradora)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTPlacaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBBuscar))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jBAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTPlacaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExcluir)
                    .addComponent(jBSair)
                    .addComponent(jBAlterar))
                .addGap(118, 118, 118))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        carregarTabela();
    }//GEN-LAST:event_jBBuscarActionPerformed


public void limpar(){
        
        //Limpa a tabela
        DefaultTableModel model = (DefaultTableModel)jTableMultas.getModel(); 
        model.setNumRows(0);
        
        //Limpando os campos de texto
        jTID.setText("");
        jTPLACA.setText("");
        jTDESCRICAO.setText("");
        jTVALOR.setText("");
        
       
        //Colocando o foco na text do nome artístico
        jTPlacaBusca.grabFocus();
      }
   
   public void carregarTabela(){
        Multas multas = new Multas();
        ArrayList<Multas> arrayDeAbastecimento = new ArrayList<Multas>(); 
        
        //Chamando a busca no banco passando a data
        arrayDeAbastecimento = multas.buscar(jTPlacaBusca.getText());
        
        //Apagando os dados da tabela para mostrar os novos
        limpar();
        
        DefaultTableModel model = (DefaultTableModel) jTableMultas.getModel();
        
        //Andando na lista de tarefa e montando as linhas do TABLEMODEL
        for(int i=0; i<arrayDeAbastecimento.size(); i++){
            
            //Criando as colunas da linha i do TABLEMODEL
            String colunas[] = new String[4];
            colunas[0] = String.valueOf(arrayDeAbastecimento.get(i).getIdmulta());
            colunas[1] = String.valueOf(arrayDeAbastecimento.get(i).getPlaca());
            colunas[2] = String.valueOf(arrayDeAbastecimento.get(i).getDescricao());
            colunas[3] = String.valueOf(arrayDeAbastecimento.get(i).getValor());
            

            //Adicionando uma linha no TABLEMODEL
            model.addRow(colunas);
        } 

        jTableMultas.setModel(model);
    }      
    
    private void jTableMultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMultasMouseClicked
        if (evt.getClickCount() == 1){

            jTID.setText((String)jTableMultas.getValueAt(jTableMultas.getSelectedRow(),0));
            jTPLACA.setText((String)jTableMultas.getValueAt(jTableMultas.getSelectedRow(),1));
            jTDESCRICAO.setText((String)jTableMultas.getValueAt(jTableMultas.getSelectedRow(),2));
            jTVALOR.setText((String)jTableMultas.getValueAt(jTableMultas.getSelectedRow(),3));
            

        }
    }//GEN-LAST:event_jTableMultasMouseClicked

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        Multas objMultas = new Multas();

        objMultas.setIdmulta(jTID.getText());
        objMultas.setPlaca(jTPLACA.getText());
        objMultas.setDescricao(jTDESCRICAO.getText());
        objMultas.setValor(jTVALOR.getText());
       
        objMultas.alterar();

        jTPlacaBusca.setText(objMultas.getPlaca());
        carregarTabela();
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        Multas objMultas = new Multas();
        objMultas.setIdmulta(jTID.getText());
        objMultas.setPlaca(jTPLACA.getText());
        objMultas.setDescricao(jTDESCRICAO.getText());
        objMultas.setValor(jTVALOR.getText());

        objMultas.excluir();

        jTPlacaBusca.setText(objMultas.getPlaca());
        carregarTabela();
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        setVisible(isClosed);
    }//GEN-LAST:event_jBSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelPLACA;
    private javax.swing.JLabel jLabelSeguradora;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTDESCRICAO;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTPLACA;
    private javax.swing.JTextField jTPlacaBusca;
    private javax.swing.JTextField jTVALOR;
    private javax.swing.JTable jTableMultas;
    // End of variables declaration//GEN-END:variables
}
