/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


/**
 *
 * @author Marcos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jDPiTask = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jButtonMotorista = new javax.swing.JButton();
        jButtonVeiculos = new javax.swing.JButton();
        jButtonViagem = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonUsuarios = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVeiculoCadastrar = new javax.swing.JMenu();
        jMenuItemVeiculoCadastrar = new javax.swing.JMenuItem();
        jMenuItemVeiculoConsultar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemMotoristaCadastrar = new javax.swing.JMenuItem();
        jMenuItemMotoristaConsultar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemUsuarioCadastrar = new javax.swing.JMenuItem();
        jMenuItemUsuarioConsultar = new javax.swing.JMenuItem();
        jMenuViagem = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Frota\\imagens\\manut.png")); // NOI18N
        jButton1.setText("Peças e Pneus");
        jButton1.setActionCommand("Viagens");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonMotorista.setIcon(new javax.swing.ImageIcon("C:\\Frota\\imagens\\motorista.png")); // NOI18N
        jButtonMotorista.setText("Motorista");
        jButtonMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMotoristaActionPerformed(evt);
            }
        });

        jButtonVeiculos.setIcon(new javax.swing.ImageIcon("C:\\Frota\\imagens\\veiculos.png")); // NOI18N
        jButtonVeiculos.setText("Veiculos");
        jButtonVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeiculosActionPerformed(evt);
            }
        });

        jButtonViagem.setIcon(new javax.swing.ImageIcon("C:\\Frota\\imagens\\local.png")); // NOI18N
        jButtonViagem.setText("Viagens");
        jButtonViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViagemActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Frota\\imagens\\abastecimento.png")); // NOI18N
        jButton5.setText("Abastecimento");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Frota\\imagens\\multas.png")); // NOI18N
        jButton8.setText("Multas");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButtonUsuarios.setIcon(new javax.swing.ImageIcon("C:\\Frota\\imagens\\usuario.png")); // NOI18N
        jButtonUsuarios.setText("Usuários");
        jButtonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDPiTaskLayout = new javax.swing.GroupLayout(jDPiTask);
        jDPiTask.setLayout(jDPiTaskLayout);
        jDPiTaskLayout.setHorizontalGroup(
            jDPiTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPiTaskLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jDPiTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDPiTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDPiTaskLayout.createSequentialGroup()
                        .addComponent(jButtonVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDPiTaskLayout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jDPiTaskLayout.setVerticalGroup(
            jDPiTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPiTaskLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jDPiTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jDPiTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(441, Short.MAX_VALUE))
        );
        jDPiTask.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPiTask.setLayer(jButtonMotorista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPiTask.setLayer(jButtonVeiculos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPiTask.setLayer(jButtonViagem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPiTask.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPiTask.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPiTask.setLayer(jButtonUsuarios, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuVeiculoCadastrar.setText("Veiculo");

        jMenuItemVeiculoCadastrar.setText("Cadastrar");
        jMenuItemVeiculoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVeiculoCadastrarActionPerformed(evt);
            }
        });
        jMenuVeiculoCadastrar.add(jMenuItemVeiculoCadastrar);

        jMenuItemVeiculoConsultar.setText("Consultar/Alterar");
        jMenuItemVeiculoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVeiculoConsultarActionPerformed(evt);
            }
        });
        jMenuVeiculoCadastrar.add(jMenuItemVeiculoConsultar);

        jMenuBar1.add(jMenuVeiculoCadastrar);

        jMenu2.setText("Motorista");

        jMenuItemMotoristaCadastrar.setText("Cadastrar");
        jMenuItemMotoristaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMotoristaCadastrarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemMotoristaCadastrar);

        jMenuItemMotoristaConsultar.setText("Consultar/alterar");
        jMenuItemMotoristaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMotoristaConsultarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemMotoristaConsultar);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Usuario");

        jMenuItemUsuarioCadastrar.setText("Cadastrar");
        jMenuItemUsuarioCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioCadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUsuarioCadastrar);

        jMenuItemUsuarioConsultar.setText("Consultar/Alterar");
        jMenuItemUsuarioConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioConsultarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUsuarioConsultar);

        jMenuBar1.add(jMenu1);

        jMenuViagem.setText("Viagem");

        jMenuItem2.setText("Cadastrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuViagem.add(jMenuItem2);

        jMenuItem1.setText("Consultar/Alterar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuViagem.add(jMenuItem1);

        jMenuBar1.add(jMenuViagem);

        jMenu7.setText("Peças");

        jMenuItem3.setText("Cadastrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuItem4.setText("Consultar/Alterar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Abastecimento");

        jMenuItem6.setText("Cadastrar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem6);

        jMenuItem5.setText("Consultar/Alterar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem5);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Multas");

        jMenuItem7.setText("Cadastrar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem7);

        jMenuItem8.setText("Consultar/Alterar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem8);

        jMenuBar1.add(jMenu9);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDPiTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDPiTask)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemVeiculoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVeiculoCadastrarActionPerformed
        VeiculoCadastrar telaVeiculo = new VeiculoCadastrar();
        jDPiTask.add(telaVeiculo);
        telaVeiculo.setVisible(true);
        //telaVeiculo.setPosicao();        
    }//GEN-LAST:event_jMenuItemVeiculoCadastrarActionPerformed

    private void jMenuItemVeiculoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVeiculoConsultarActionPerformed
        VeiculoConsulta telaVeiculoConsulta = new VeiculoConsulta();
        jDPiTask.add(telaVeiculoConsulta);
        telaVeiculoConsulta.setVisible(true);
        //telaVeiculo.setPosicao(); 
    }//GEN-LAST:event_jMenuItemVeiculoConsultarActionPerformed

    private void jMenuItemMotoristaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMotoristaCadastrarActionPerformed

        MotoristaCadastrar tela = new MotoristaCadastrar();
        jDPiTask.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemMotoristaCadastrarActionPerformed

    private void jMenuItemMotoristaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMotoristaConsultarActionPerformed

         MotoristaConsulta tela = new MotoristaConsulta();
        jDPiTask.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemMotoristaConsultarActionPerformed

    private void jMenuItemUsuarioCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioCadastrarActionPerformed
        UsuarioCadastrar tela = new UsuarioCadastrar();
        jDPiTask.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemUsuarioCadastrarActionPerformed

    private void jMenuItemUsuarioConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioConsultarActionPerformed
        UsuarioConsultar tela = new UsuarioConsultar();
        jDPiTask.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuarioConsultarActionPerformed

    private void jButtonMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMotoristaActionPerformed

        MotoristaMenu motoristaMenu = new MotoristaMenu();
        jDPiTask.add(motoristaMenu);
        motoristaMenu.setVisible(true);
        
    }//GEN-LAST:event_jButtonMotoristaActionPerformed

    private void jButtonVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeiculosActionPerformed
        VeiculoMenu veiculoMenu = new VeiculoMenu();
        jDPiTask.add(veiculoMenu);
        veiculoMenu.setVisible(true);

    }//GEN-LAST:event_jButtonVeiculosActionPerformed

    private void jButtonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuariosActionPerformed

        UsuarioMenu usuarioMenu = new UsuarioMenu();
        jDPiTask.add(usuarioMenu);
        usuarioMenu.setVisible(true);

        
    }//GEN-LAST:event_jButtonUsuariosActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        dispose();
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jButtonViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViagemActionPerformed
        ViagemMenu viagemMenu = new ViagemMenu();
        jDPiTask.add(viagemMenu);
        viagemMenu.setVisible(true);
        
        
    }//GEN-LAST:event_jButtonViagemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        PecasMenu pecasMenu = new PecasMenu();
        jDPiTask.add(pecasMenu);
        pecasMenu.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ViagemCadastrar viagemCadastrar = new ViagemCadastrar();
        jDPiTask.add(viagemCadastrar);
        viagemCadastrar.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        PecasCadastro pecasCadastro = new PecasCadastro();
        jDPiTask.add(pecasCadastro);
        pecasCadastro.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        PecasConsulta pecasConsulta = new PecasConsulta();
        jDPiTask.add(pecasConsulta);
        pecasConsulta.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        MultasMenu multasMenu = new MultasMenu();
        jDPiTask.add(multasMenu);
        multasMenu.setVisible(true);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AbastecimentoMenu abastecimentoMenu = new AbastecimentoMenu();
        jDPiTask.add(abastecimentoMenu);
        abastecimentoMenu.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        AbastecimentoCadastrar abastecimentoCadastrar = new AbastecimentoCadastrar();
        jDPiTask.add(abastecimentoCadastrar);
        abastecimentoCadastrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        AbastecimentoConsultar abastecimentoConsultar = new AbastecimentoConsultar();
        jDPiTask.add(abastecimentoConsultar);
        abastecimentoConsultar.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        MultasCadastrar multasCadastrar = new MultasCadastrar();
        jDPiTask.add(multasCadastrar);
        multasCadastrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        MultasConsultar multasConsultar = new MultasConsultar();
        jDPiTask.add(multasConsultar);
        multasConsultar.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ViagemConsultar viagemConsultar = new ViagemConsultar();
        jDPiTask.add(viagemConsultar);
        viagemConsultar.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonMotorista;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JButton jButtonVeiculos;
    private javax.swing.JButton jButtonViagem;
    private javax.swing.JDesktopPane jDPiTask;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemMotoristaCadastrar;
    private javax.swing.JMenuItem jMenuItemMotoristaConsultar;
    private javax.swing.JMenuItem jMenuItemUsuarioCadastrar;
    private javax.swing.JMenuItem jMenuItemUsuarioConsultar;
    private javax.swing.JMenuItem jMenuItemVeiculoCadastrar;
    private javax.swing.JMenuItem jMenuItemVeiculoConsultar;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuVeiculoCadastrar;
    private javax.swing.JMenu jMenuViagem;
    // End of variables declaration//GEN-END:variables
}
