/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.Usuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos
 */
public class UsuarioConsultar extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioConsultar
     */
    public UsuarioConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jTLoginBuscar = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jTLOGIN = new javax.swing.JTextField();
        jLabelMarca = new javax.swing.JLabel();
        jLabelPLACA = new javax.swing.JLabel();
        jTNOME = new javax.swing.JTextField();
        jLabelSeguro = new javax.swing.JLabel();
        jTSENHACONFIR = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTSENHA = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jTPERFIL = new javax.swing.JTextField();
        jLabelStatus1 = new javax.swing.JLabel();
        jTSTATUS = new javax.swing.JTextField();
        jBExcluir = new javax.swing.JButton();

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jLabel1.setText("LOGIN");

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "LOGIN", "NOME COMPL.", "SENHA", "PERFIL", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuario);

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Usuario"));

        jLabel5.setText("ID");

        jTID.setEditable(false);
        jTID.setBackground(new java.awt.Color(255, 255, 204));

        jLabelMarca.setText("LOGIN");

        jLabelPLACA.setText("NOME COMPLETO");

        jLabelSeguro.setText("CONFIR. SENHA");

        jLabelCidade.setText("SENHA");

        jLabelStatus.setText("PERFIL");

        jLabelStatus1.setText("STATUS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPLACA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTSENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSeguro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTSENHACONFIR, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPERFIL, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelStatus1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTSTATUS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMarca)
                    .addComponent(jTLOGIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPLACA)
                    .addComponent(jTNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTSENHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSeguro)
                    .addComponent(jTSENHACONFIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jTPERFIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus1)
                    .addComponent(jTSTATUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTLoginBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jBAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBExcluir)
                                .addGap(74, 74, 74)
                                .addComponent(jBSair)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTLoginBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAlterar)
                    .addComponent(jBExcluir)
                    .addComponent(jBSair))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
  public void limpar(){
        
        //Limpa a tabela
        DefaultTableModel model = (DefaultTableModel)jTableUsuario.getModel(); 
        model.setNumRows(0);
        
        //Limpando os campos de texto
        jTID.setText("");
        jTLOGIN.setText("");
        jTNOME.setText("");
        jTSENHA.setText("");
        jTPERFIL.setText("");
        jTSTATUS.setText("");
        
        
        //Colocando o foco na text do nome artístico
        jTLoginBuscar.grabFocus();
      }
      
     
    
   
   public void carregarTabela(){
        Usuario usuario = new Usuario();
        ArrayList<Usuario> arrayDeUsuarios = new ArrayList<Usuario>(); 
        
        //Chamando a busca no banco passando a data
        arrayDeUsuarios = usuario.buscar(jTLoginBuscar.getText());
        
        //Apagando os dados da tabela para mostrar os novos
        limpar();
        
        DefaultTableModel model = (DefaultTableModel) jTableUsuario.getModel();
        
        //Andando na lista de tarefa e montando as linhas do TABLEMODEL
        for(int i=0; i<arrayDeUsuarios.size(); i++){
            
            //Criando as colunas da linha i do TABLEMODEL
            String colunas[] = new String[6];
            colunas[0] = String.valueOf(arrayDeUsuarios.get(i).getCodigo());
            colunas[1] = String.valueOf(arrayDeUsuarios.get(i).getLogin());
            colunas[2] = String.valueOf(arrayDeUsuarios.get(i).getNome());
            colunas[3] = String.valueOf(arrayDeUsuarios.get(i).getSenha());
            colunas[4] = String.valueOf(arrayDeUsuarios.get(i).getPerfil());
            colunas[5] = String.valueOf(arrayDeUsuarios.get(i).getStatus());
            
            
            
            
            //Adicionando uma linha no TABLEMODEL
            model.addRow(colunas);
        } 

        jTableUsuario.setModel(model);
    }    
    
    
    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        setVisible(isClosed);
    }//GEN-LAST:event_jBSairActionPerformed

    private void jTableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuarioMouseClicked
        if (evt.getClickCount() == 1){

            jTID.setText((String)jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(),0));
            jTLOGIN.setText((String)jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(),1));
            jTNOME.setText((String)jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(),2));
            jTSENHA.setText((String)jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(),3));
            jTSENHACONFIR.setText((String)jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(),3));
            jTPERFIL.setText((String)jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(),4));
            jTSTATUS.setText((String)jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(),5));

        }
    }//GEN-LAST:event_jTableUsuarioMouseClicked

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        carregarTabela();
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        Usuario objUsuario = new Usuario();
     
        objUsuario.setCodigo(jTID.getText());
        objUsuario.setLogin(jTLOGIN.getText());
        objUsuario.setNome(jTNOME.getText());
        objUsuario.setSenha(jTSENHA.getText());
        objUsuario.setPerfil(jTPERFIL.getText());
        objUsuario.setStatus(jTSTATUS.getText());
        objUsuario.alterar();

        jTLoginBuscar.setText(objUsuario.getLogin());
        carregarTabela();
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        Usuario objUsuario = new Usuario();
        
        objUsuario.setLogin(jTLOGIN.getText());
        objUsuario.setNome(jTNOME.getText());
        objUsuario.setSenha(jTSENHA.getText());
        objUsuario.setPerfil(jTPERFIL.getText());
        objUsuario.setStatus(jTSTATUS.getText());
        

        objUsuario.excluir();

        jTLoginBuscar.setText(objUsuario.getLogin());
        carregarTabela();
    }//GEN-LAST:event_jBExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelPLACA;
    private javax.swing.JLabel jLabelSeguro;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStatus1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTLOGIN;
    private javax.swing.JTextField jTLoginBuscar;
    private javax.swing.JTextField jTNOME;
    private javax.swing.JTextField jTPERFIL;
    private javax.swing.JTextField jTSENHA;
    private javax.swing.JTextField jTSENHACONFIR;
    private javax.swing.JTextField jTSTATUS;
    private javax.swing.JTable jTableUsuario;
    // End of variables declaration//GEN-END:variables
}
