/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.Veiculo;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Marcos
 */
public class VeiculoConsulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form VeiculoConsulta
     */
    public VeiculoConsulta() {
        initComponents();
    }
    
    
     public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBExcluir = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVEICULO = new javax.swing.JTable();
        jTPlacaBusca = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelModelo = new javax.swing.JLabel();
        jTMODELO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jTMARCA = new javax.swing.JTextField();
        jLabelMarca = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTSeguradora = new javax.swing.JTextArea();
        jLabelPLACA = new javax.swing.JLabel();
        jTPLACA = new javax.swing.JTextField();
        jLabelSeguro = new javax.swing.JLabel();
        jTSeguro = new javax.swing.JTextField();
        jLabelSeguradora = new javax.swing.JLabel();
        jTDataFim = new javax.swing.JTextField();
        jTAnoFab = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTCidadeUF = new javax.swing.JTextField();
        jLabelAno = new javax.swing.JLabel();
        jTDataIni = new javax.swing.JTextField();
        jLabelDataIni = new javax.swing.JLabel();
        jLabelDataFim = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jTSTATUS = new javax.swing.JTextField();

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jLabel1.setText("PLACA");

        jTableVEICULO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "MARCA", "MODELO", "PLACA", "ANO_FAB", "CIDADE", "SEGURO", "DATA_INI", "DATA_FIM", "SEGURADORA", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVEICULO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVEICULOMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVEICULO);

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Viagem"));

        jLabelModelo.setText("MODELO");

        jLabel5.setText("ID");

        jTID.setEditable(false);
        jTID.setBackground(new java.awt.Color(255, 255, 204));

        jLabelMarca.setText("MARCA");

        jTSeguradora.setColumns(20);
        jTSeguradora.setRows(5);
        jScrollPane2.setViewportView(jTSeguradora);

        jLabelPLACA.setText("PLACA");

        jLabelSeguro.setText("SEGURO");

        jLabelSeguradora.setText("SEGURADORA");

        jLabelCidade.setText("CIDADE/UF");

        jLabelAno.setText("Ano/Fab.");

        jLabelDataIni.setText("DATA INI.");

        jLabelDataFim.setText("DATA FIM");

        jLabelStatus.setText("STATUS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTCidadeUF))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelPLACA)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTPLACA, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelMarca)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTMODELO, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTAnoFab, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSeguradora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSeguro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDataIni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDataFim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTSTATUS, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTMODELO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelModelo)
                        .addComponent(jLabelMarca))
                    .addComponent(jTMARCA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPLACA)
                    .addComponent(jTPLACA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAno)
                    .addComponent(jTAnoFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTCidadeUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDataIni)
                        .addComponent(jLabelDataFim))
                    .addComponent(jLabelSeguro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSeguradora)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelStatus)
                    .addComponent(jTSTATUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTPlacaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBBuscar))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jBAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTPlacaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExcluir)
                    .addComponent(jBSair)
                    .addComponent(jBAlterar))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


      public void limpar(){
        
        //Limpa a tabela
        DefaultTableModel model = (DefaultTableModel)jTableVEICULO.getModel(); 
        model.setNumRows(0);
        
        //Limpando os campos de texto
        jTID.setText("");
        jTMODELO.setText("");
        jTMARCA.setText("");
        jTPLACA.setText("");
        jTAnoFab.setText("");
        jTCidadeUF.setText("");
        jTSeguro.setText("");
        jTDataIni.setText("");
        jTDataFim.setText("");
        jTSeguradora.setText("");
        jTSTATUS.setText("");
        
        //Colocando o foco na text do nome artístico
        jTMARCA.grabFocus();
      }
      
     
    
   
   public void carregarTabela(){
        Veiculo veiculo = new Veiculo();
        ArrayList<Veiculo> arrayDeVeiculos = new ArrayList<Veiculo>(); 
        
        //Chamando a busca no banco passando a data
        arrayDeVeiculos = veiculo.buscar(jTPlacaBusca.getText());
        
        //Apagando os dados da tabela para mostrar os novos
        limpar();
        
        DefaultTableModel model = (DefaultTableModel) jTableVEICULO.getModel();
        
        //Andando na lista de tarefa e montando as linhas do TABLEMODEL
        for(int i=0; i<arrayDeVeiculos.size(); i++){
            
            //Criando as colunas da linha i do TABLEMODEL
            String colunas[] = new String[11];
            colunas[0] = String.valueOf(arrayDeVeiculos.get(i).getCodigo());
            colunas[1] = String.valueOf(arrayDeVeiculos.get(i).getMarca());
            colunas[2] = String.valueOf(arrayDeVeiculos.get(i).getModelo());
            colunas[3] = String.valueOf(arrayDeVeiculos.get(i).getPlaca());
            colunas[4] = String.valueOf(arrayDeVeiculos.get(i).getAno_fab_mod());
            colunas[5] = String.valueOf(arrayDeVeiculos.get(i).getCidade_estado());
            colunas[6] = String.valueOf(arrayDeVeiculos.get(i).getSeguro());
            colunas[7] = String.valueOf(arrayDeVeiculos.get(i).getInicio_seguro());
            colunas[8] = String.valueOf(arrayDeVeiculos.get(i).getVencimento_seguro());
            colunas[9] = String.valueOf(arrayDeVeiculos.get(i).getSeguradora());
            colunas[10] = String.valueOf(arrayDeVeiculos.get(i).getStatus());
            
            
            
            //Adicionando uma linha no TABLEMODEL
            model.addRow(colunas);
        } 

        jTableVEICULO.setModel(model);
    }
    
    

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        Veiculo objVeiculo = new Veiculo();
        objVeiculo.setCodigo(jTID.getText());
        objVeiculo.setMarca(jTMARCA.getText());
        objVeiculo.setModelo(jTMODELO.getText());
        objVeiculo.setPlaca(jTPLACA.getText());
        objVeiculo.setAno_fab_mod(jTAnoFab.getText());
        objVeiculo.setCidade_estado(jTCidadeUF.getText());
        objVeiculo.setSeguro(jTSeguro.getText());
        objVeiculo.setInicio_seguro(jTDataIni.getText());
        objVeiculo.setVencimento_seguro(jTDataFim.getText());
        objVeiculo.setSeguradora(jTSeguradora.getText());
        objVeiculo.setStatus(jTSTATUS.getText());
        
        objVeiculo.excluir();

        jTPlacaBusca.setText(objVeiculo.getPlaca());
        carregarTabela();
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        setVisible(isClosed);
    }//GEN-LAST:event_jBSairActionPerformed

    private void jTableVEICULOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVEICULOMouseClicked
        if (evt.getClickCount() == 1){

            jTID.setText((String)jTableVEICULO.getValueAt(jTableVEICULO.getSelectedRow(),0));
            jTMARCA.setText((String)jTableVEICULO.getValueAt(jTableVEICULO.getSelectedRow(),1));
            jTMODELO.setText((String)jTableVEICULO.getValueAt(jTableVEICULO.getSelectedRow(),2));
            jTPLACA.setText((String)jTableVEICULO.getValueAt(jTableVEICULO.getSelectedRow(),3));
            jTAnoFab.setText((String)jTableVEICULO.getValueAt(jTableVEICULO.getSelectedRow(),4));
            jTCidadeUF.setText((String)jTableVEICULO.getValueAt(jTableVEICULO.getSelectedRow(),5));
            jTSeguro.setText((String)jTableVEICULO.getValueAt(jTableVEICULO.getSelectedRow(),6));
            jTDataIni.setText((String)jTableVEICULO.getValueAt(jTableVEICULO.getSelectedRow(),7));
            jTDataFim.setText((String)jTableVEICULO.getValueAt(jTableVEICULO.getSelectedRow(),8));
            jTSeguradora.setText((String)jTableVEICULO.getValueAt(jTableVEICULO.getSelectedRow(),9));
            jTSTATUS.setText((String)jTableVEICULO.getValueAt(jTableVEICULO.getSelectedRow(),10));

        }
    }//GEN-LAST:event_jTableVEICULOMouseClicked

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        carregarTabela();
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        Veiculo objVeiculo = new Veiculo();
        
        objVeiculo.setCodigo(jTID.getText());
        objVeiculo.setMarca(jTMARCA.getText());
        objVeiculo.setModelo(jTMODELO.getText());
        objVeiculo.setPlaca(jTPLACA.getText());
        objVeiculo.setAno_fab_mod(jTAnoFab.getText());
        objVeiculo.setCidade_estado(jTCidadeUF.getText());
        objVeiculo.setSeguro(jTSeguro.getText());
        objVeiculo.setInicio_seguro(jTDataIni.getText());
        objVeiculo.setVencimento_seguro(jTDataFim.getText());
        objVeiculo.setSeguradora(jTSeguradora.getText());
        objVeiculo.setStatus(jTSTATUS.getText());
        objVeiculo.alterar();

        jTPlacaBusca.setText(objVeiculo.getPlaca());
        carregarTabela();
    }//GEN-LAST:event_jBAlterarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDataFim;
    private javax.swing.JLabel jLabelDataIni;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPLACA;
    private javax.swing.JLabel jLabelSeguradora;
    private javax.swing.JLabel jLabelSeguro;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTAnoFab;
    private javax.swing.JTextField jTCidadeUF;
    private javax.swing.JTextField jTDataFim;
    private javax.swing.JTextField jTDataIni;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTMARCA;
    private javax.swing.JTextField jTMODELO;
    private javax.swing.JTextField jTPLACA;
    private javax.swing.JTextField jTPlacaBusca;
    private javax.swing.JTextField jTSTATUS;
    private javax.swing.JTextArea jTSeguradora;
    private javax.swing.JTextField jTSeguro;
    private javax.swing.JTable jTableVEICULO;
    // End of variables declaration//GEN-END:variables
}
