/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.Viagem;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos
 */
public class ViagemConsultar extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViagemConsultar
     */
    public ViagemConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
          public void limpar(){
        
        //Limpa a tabela
        DefaultTableModel model = (DefaultTableModel)jTableVIAGEM.getModel(); 
        model.setNumRows(0);
        
        //Limpando os campos de texto
        jTID.setText("");
        jTMOTORISTA.setText("");
        jTCPF.setText("");
        jTORIGEM.setText("");
        jTDESTINO.setText("");
        jTPLACA.setText("");
        jTDataIda.setText("");
        jTDataVolta.setText("");
        jTDetalhesViagem.setText("");
        jTSTATUS.setText("");
        
        //Colocando o foco na text do nome artístico
        jTMOTORISTA.grabFocus();
      }
      
   public void carregarTabela(){
        Viagem viagem = new Viagem();
        ArrayList<Viagem> arrayDeViagem = new ArrayList<Viagem>(); 
        
        //Chamando a busca no banco passando a data
        arrayDeViagem = viagem.buscar(jTViagemBuscar.getText());
        
        //Apagando os dados da tabela para mostrar os novos
        limpar();
        
        DefaultTableModel model = (DefaultTableModel) jTableVIAGEM.getModel();
        
        //Andando na lista de tarefa e montando as linhas do TABLEMODEL
        for(int i=0; i<arrayDeViagem.size(); i++){
            
            //Criando as colunas da linha i do TABLEMODEL
            String colunas[] = new String[10];
            colunas[0] = String.valueOf(arrayDeViagem.get(i).getIdviagem());
            colunas[1] = String.valueOf(arrayDeViagem.get(i).getMotorista());
            colunas[2] = String.valueOf(arrayDeViagem.get(i).getCpf());
            colunas[3] = String.valueOf(arrayDeViagem.get(i).getOrigem());
            colunas[4] = String.valueOf(arrayDeViagem.get(i).getDestino());
            colunas[5] = String.valueOf(arrayDeViagem.get(i).getPlacaveiculo());
            colunas[6] = String.valueOf(arrayDeViagem.get(i).getDataida());
            colunas[7] = String.valueOf(arrayDeViagem.get(i).getDatavolta());
            colunas[8] = String.valueOf(arrayDeViagem.get(i).getDetalhesviagem());
            colunas[9] = String.valueOf(arrayDeViagem.get(i).getStatus());
            
            
            
            //Adicionando uma linha no TABLEMODEL
            model.addRow(colunas);
        } 

        jTableVIAGEM.setModel(model);
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBExcluir = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVIAGEM = new javax.swing.JTable();
        jTViagemBuscar = new javax.swing.JTextField();
        jBBuscarNroViagem = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelModelo = new javax.swing.JLabel();
        jTCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jTMOTORISTA = new javax.swing.JTextField();
        jLabelMarca = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTDetalhesViagem = new javax.swing.JTextArea();
        jLabelPLACA = new javax.swing.JLabel();
        jTORIGEM = new javax.swing.JTextField();
        jLabelSeguro = new javax.swing.JLabel();
        jTDataIda = new javax.swing.JTextField();
        jLabelSeguradora = new javax.swing.JLabel();
        jTDESTINO = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTPLACA = new javax.swing.JTextField();
        jLabelAno = new javax.swing.JLabel();
        jTDataVolta = new javax.swing.JTextField();
        jLabelDataIni = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jTSTATUS = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(600, 499));

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jLabel1.setText("Nro Viagem");

        jTableVIAGEM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID VIAGEM", "MOTORISTA", "CPF", "ORIGEM", "DESTINO", "PLACA VEICULO", "DATA IDA", "DATA VOLTA", "DETALHES", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVIAGEM.setName(""); // NOI18N
        jTableVIAGEM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVIAGEMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVIAGEM);

        jBBuscarNroViagem.setText("Buscar");
        jBBuscarNroViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarNroViagemActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Viagem"));

        jLabelModelo.setText("CPF");

        jLabel5.setText("ID VIAGEM");

        jTID.setEditable(false);
        jTID.setBackground(new java.awt.Color(255, 255, 204));

        jLabelMarca.setText("MOTORISTA");

        jTDetalhesViagem.setColumns(20);
        jTDetalhesViagem.setRows(5);
        jScrollPane2.setViewportView(jTDetalhesViagem);

        jLabelPLACA.setText("ORIGEM");

        jLabelSeguro.setText("DATA IDA");

        jLabelSeguradora.setText("DETALHES VIAGEM");

        jLabelCidade.setText("PLACA VEICULO");

        jLabelAno.setText("DESTINO");

        jLabelDataIni.setText("DATA VOLTA");

        jLabelStatus.setText("STATUS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTPLACA))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelPLACA)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTORIGEM, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelMarca)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTMOTORISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTDESTINO, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSeguradora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSeguro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTDataIda, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDataIni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTDataVolta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTSTATUS, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelModelo)
                        .addComponent(jLabelMarca))
                    .addComponent(jTMOTORISTA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPLACA)
                    .addComponent(jTORIGEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAno)
                    .addComponent(jTDESTINO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTPLACA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTDataIda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTDataVolta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDataIni))
                    .addComponent(jLabelSeguro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSeguradora)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelStatus)
                    .addComponent(jTSTATUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jBAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBSair)
                .addContainerGap(336, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTViagemBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscarNroViagem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTViagemBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarNroViagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExcluir)
                    .addComponent(jBSair)
                    .addComponent(jBAlterar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        Viagem objViagem = new Viagem();
        objViagem.setIdviagem(jTID.getText());
        objViagem.setMotorista(jTMOTORISTA.getText());
        objViagem.setCpf(jTCPF.getText());
        objViagem.setOrigem(jTORIGEM.getText());
        objViagem.setDestino(jTDESTINO.getText());
        objViagem.setPlacaveiculo(jTPLACA.getText());
        objViagem.setDataida(jTDataIda.getText());
        objViagem.setDatavolta(jTDataVolta.getText());
        objViagem.setDetalhesviagem(jTDetalhesViagem.getText());
        objViagem.setStatus(jTSTATUS.getText());

        objViagem.excluir();

        jTViagemBuscar.setText(objViagem.getIdviagem());
        carregarTabela();
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        setVisible(isClosed);
    }//GEN-LAST:event_jBSairActionPerformed

    private void jTableVIAGEMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVIAGEMMouseClicked
        if (evt.getClickCount() == 1){

            jTID.setText((String)jTableVIAGEM.getValueAt(jTableVIAGEM.getSelectedRow(),0));
            jTMOTORISTA.setText((String)jTableVIAGEM.getValueAt(jTableVIAGEM.getSelectedRow(),1));
            jTCPF.setText((String)jTableVIAGEM.getValueAt(jTableVIAGEM.getSelectedRow(),2));
            jTORIGEM.setText((String)jTableVIAGEM.getValueAt(jTableVIAGEM.getSelectedRow(),3));
            jTDESTINO.setText((String)jTableVIAGEM.getValueAt(jTableVIAGEM.getSelectedRow(),4));
            jTPLACA.setText((String)jTableVIAGEM.getValueAt(jTableVIAGEM.getSelectedRow(),5));
            jTDataIda.setText((String)jTableVIAGEM.getValueAt(jTableVIAGEM.getSelectedRow(),6));
            jTDataVolta.setText((String)jTableVIAGEM.getValueAt(jTableVIAGEM.getSelectedRow(),7));
            jTDetalhesViagem.setText((String)jTableVIAGEM.getValueAt(jTableVIAGEM.getSelectedRow(),8));
            jTSTATUS.setText((String)jTableVIAGEM.getValueAt(jTableVIAGEM.getSelectedRow(),9));

        }
    }//GEN-LAST:event_jTableVIAGEMMouseClicked

    private void jBBuscarNroViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarNroViagemActionPerformed
        carregarTabela();
    }//GEN-LAST:event_jBBuscarNroViagemActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        Viagem objViagem = new Viagem();

        objViagem.setIdviagem(jTID.getText());
        objViagem.setMotorista(jTMOTORISTA.getText());
        objViagem.setCpf(jTCPF.getText());
        objViagem.setOrigem(jTORIGEM.getText());
        objViagem.setDestino(jTDESTINO.getText());
        objViagem.setPlacaveiculo(jTPLACA.getText());
        objViagem.setDataida(jTDataIda.getText());
        objViagem.setDatavolta(jTDataVolta.getText());
        objViagem.setDetalhesviagem(jTDetalhesViagem.getText());
        objViagem.setStatus(jTSTATUS.getText());
        objViagem.alterar();

        jTViagemBuscar.setText(objViagem.getIdviagem());
        carregarTabela();
    }//GEN-LAST:event_jBAlterarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBBuscarNroViagem;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDataIni;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPLACA;
    private javax.swing.JLabel jLabelSeguradora;
    private javax.swing.JLabel jLabelSeguro;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTCPF;
    private javax.swing.JTextField jTDESTINO;
    private javax.swing.JTextField jTDataIda;
    private javax.swing.JTextField jTDataVolta;
    private javax.swing.JTextArea jTDetalhesViagem;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTMOTORISTA;
    private javax.swing.JTextField jTORIGEM;
    private javax.swing.JTextField jTPLACA;
    private javax.swing.JTextField jTSTATUS;
    private javax.swing.JTextField jTViagemBuscar;
    private javax.swing.JTable jTableVIAGEM;
    // End of variables declaration//GEN-END:variables
}
